title: DANDOENG  :)
description: Dandoeng Personal Website Form Jekyll & theme by brianmaierjr (built with SASS / COMPASS / SUSY)

url: https://dandoeng.tech/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Projects
    url: /projects
  - title: Articles
    url: /articles
  - title: Certificates
    url: /certificates

social:
  github: irvandandung
  twitter: irvandandung
  facebook: irvandandung
  email: irvandandung1@gmail.com
  linkedin: muhamad-irvan-dandung-7b2964167

google_analytics: "UA-58263416-1"

disqus:
    shortname: https-irvandandung-github-com
